import os
import pandas as pd
import datetime
import altair as alt
import shutil
import time
from fpdf import FPDF
from dotenv import load_dotenv

# Import Data Loader AND Cleaner
from utils.data_loader import load_data 
from utils.data_cleaner import clean_db_data

# Import Graph Logic
from utils.graph_altair import (
    plot_top10_sites_by_downtime_altair,
    plot_repeated_sites_comparison,
    plot_top_repeated_sites_bar
)

# --- CONFIGURATION ---
load_dotenv()
BASE_DIR = os.getenv("BASE_DIR")
OUTPUT_FOLDER = os.path.join(BASE_DIR, "Output")
DATA_SOURCE = os.getenv("DATA_SOURCE", "db").upper()

os.makedirs(OUTPUT_FOLDER, exist_ok=True)

class PDF(FPDF):
    def header(self):
        # We will handle the header manually in the body to control exact placement
        pass

    def footer(self):
        self.set_y(-10)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 5, f'Generated by Automation Pipeline | Source: {DATA_SOURCE}', 0, 0, 'R')

def save_altair_chart(chart, filename, width_px, height_px):
    """Saves an Altair chart as a PNG file with specific dimensions."""
    final_chart = chart.properties(
        background='white',
        width=width_px,
        height=height_px
    )
    # scale_factor=2 ensures high quality for PDF printing
    final_chart.save(filename, engine="vl-convert", scale_factor=2.0)
    return filename

def create_charts(df, current_month_period, prev_month_period):
    """Generates charts resized for the Landscape layout."""
    charts = {}
    temp_dir = os.path.join(OUTPUT_FOLDER, "temp")
    os.makedirs(temp_dir, exist_ok=True)

    # Filter Data
    curr_df = df[df['month'] == current_month_period].copy()
    
    # -------------------------------------------------------
    # CHART 1: Top 10 Downtime (Row 1 Left - Wide)
    # Target: 60% of Page Width. Approx 600px wide for the image.
    # -------------------------------------------------------
    chart1 = plot_top10_sites_by_downtime_altair(curr_df, current_month_period)
    # Remove Altair title since we add it in PDF
    chart1 = chart1.properties(title="") 
    path1 = os.path.join(temp_dir, "chart1_downtime.png")
    # Wider chart for the top row
    save_altair_chart(chart1, path1, width_px=500, height_px=220) 
    charts['downtime'] = path1

    # -------------------------------------------------------
    # CHART 2: Comparison (Row 2 Left - Half)
    # Target: 50% Page Width.
    # -------------------------------------------------------
    chart2 = plot_repeated_sites_comparison(df, current_month_period, prev_month_period)
    chart2 = chart2.properties(title="")
    path2 = os.path.join(temp_dir, "chart2_comparison.png")
    save_altair_chart(chart2, path2, width_px=350, height_px=200)
    charts['comparison'] = path2

    # -------------------------------------------------------
    # CHART 3: Frequency (Row 2 Right - Half)
    # Target: 50% Page Width.
    # -------------------------------------------------------
    chart3 = plot_top_repeated_sites_bar(curr_df, current_month_period)
    chart3 = chart3.properties(title="")
    path3 = os.path.join(temp_dir, "chart3_frequency.png")
    save_altair_chart(chart3, path3, width_px=350, height_px=200)
    charts['frequency'] = path3

    return charts

def generate_monthly_report():
    today = datetime.date.today()
    
    # Calculate target months
    first_of_this_month = today.replace(day=1)
    last_month_end = first_of_this_month - datetime.timedelta(days=1)
    
    target_period = pd.Period(last_month_end, freq='M')
    target_month_str = target_period.strftime("%B %Y")
    target_month_short = target_period.strftime("%b %Y")
    
    prev_period = target_period - 1
    prev_month_str = prev_period.strftime("%B %Y")
    prev_month_short = prev_period.strftime("%b %Y")

    # TEST OVERRIDE (Optional)
    # target_month_str = "2025-11"
    # target_period = pd.Period(target_month_str, freq='M')
    # prev_period = target_period - 1

    print(f"📊 Generating Landscape Report for: {target_month_str}")

    # 1. Load & Clean
    try:
        df_raw = load_data()
        if df_raw.empty: return
        df = clean_db_data(df_raw)
    except Exception as e:
        print(f"❌ ERROR: {e}")
        return

    # 2. Generate Charts
    print("🎨 Generating charts...")
    try:
        chart_paths = create_charts(df, target_period, prev_period)
    except Exception as e:
        import traceback
        traceback.print_exc()
        return

    # 3. Create PDF (Landscape A4)
    # A4 Landscape Dimensions: Width ~297mm, Height ~210mm
    pdf = PDF(orientation='L', unit='mm', format='A4')
    pdf.add_page()
    
    # --- PAGE LAYOUT LOGIC ---
    
    # MARGINS
    margin_x = 10
    margin_y = 10
    page_width = 297 - (2 * margin_x) # 277mm usable width
    
    # --- ROW 1: HEADER & MAIN CHART ---
    # Layout: [ Chart 1 (60%) ] [ Metrics & Title (40%) ]
    
    # Define widths
    col1_width = page_width * 0.70
    col2_width = page_width * 0.30
    row1_height = 85 # mm

    # >>> Column 2: TITLE & METRICS (Right Side)
    # We draw this first or second, position is absolute
    pdf.set_xy(margin_x + col1_width + 5, margin_y)
    
    # Title
    pdf.set_font("Arial", 'B', 20)
    pdf.cell(col2_width, 10, "Monthly Outage Report", 0, 1, 'L')
    
    pdf.set_font("Arial", 'B', 14)
    pdf.set_text_color(100, 100, 100) # Grey
    pdf.set_xy(margin_x + col1_width + 5, margin_y + 10)
    pdf.cell(col2_width, 8, f"Period: {target_month_str}", 0, 1, 'L')
    
    # Metrics Box
    curr_df = df[df['month'] == target_period]
    total_incidents = len(curr_df)
    total_downtime = curr_df['duration_hours'].sum()
    avg_downtime = curr_df['duration_hours'].mean() if total_incidents > 0 else 0
    
    pdf.set_xy(margin_x + col1_width + 5, margin_y + 25)
    pdf.set_text_color(0, 0, 0) # Black
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(col2_width, 8, "Key Statistics:", 0, 1, 'L')
    
    pdf.set_font("Arial", '', 11)
    pdf.set_xy(margin_x + col1_width + 10, margin_y + 35)
    # CHANGE: Replaced '•' with '-' to fix UnicodeEncodeError
    pdf.cell(col2_width, 6, f"- Total Incidents: {total_incidents}", 0, 1, 'L')
    
    pdf.set_xy(margin_x + col1_width + 10, margin_y + 42)
    pdf.cell(col2_width, 6, f"- Total Downtime: {total_downtime:.1f} hours", 0, 1, 'L')
    
    pdf.set_xy(margin_x + col1_width + 10, margin_y + 49)
    pdf.cell(col2_width, 6, f"- Avg Resolution: {avg_downtime:.1f} hours", 0, 1, 'L')
    
    # >>> Column 1: CHART 1 (Left Side)
    # Title for Chart 1
    pdf.set_xy(margin_x, margin_y)
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(col1_width, 8, f"Top 10 Highest Downtime for {target_month_str}", 0, 1, 'L')
    
    # Image 1
    # x, y, w, h
    pdf.image(chart_paths['downtime'], x=margin_x, y=margin_y + 8, w=col1_width - 5, h=row1_height - 10)


    # --- ROW 2: COMPARISON & FREQUENCY ---
    # Layout: [ Chart 2 (50%) ] [ Chart 3 (50%) ]
    
    row2_y = margin_y + row1_height + 5 # Start below row 1
    col_half_width = page_width / 2
    row2_height = 85 # mm

    # >>> Chart 2 (Left)
    pdf.set_xy(margin_x, row2_y)
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(col_half_width, 8, f"Top 10 Repeated Sites by {target_month_short} and {prev_month_short}", 0, 1, 'L')
    
    pdf.image(chart_paths['comparison'], x=margin_x, y=row2_y + 8, w=col_half_width - 5, h=row2_height - 10)

    # >>> Chart 3 (Right)
    pdf.set_xy(margin_x + col_half_width, row2_y)
    pdf.cell(col_half_width, 8, f"Top 10 Most Repeated Sites for {target_month_str}", 0, 1, 'L')
    
    pdf.image(chart_paths['frequency'], x=margin_x + col_half_width, y=row2_y + 8, w=col_half_width - 5, h=row2_height - 10)

    # 4. Save
    filename = f"Monthly_Outage_Report_{target_month_str}.pdf"
    output_path = os.path.join(OUTPUT_FOLDER, filename)
    pdf.output(output_path)
    print(f"✅ SUCCESS: Report generated at {output_path}")

    # 5. Cleanup
    time.sleep(1)
    temp_dir = os.path.join(OUTPUT_FOLDER, "temp")
    if os.path.exists(temp_dir):
        try:
            shutil.rmtree(temp_dir)
        except Exception:
            pass

if __name__ == "__main__":
    generate_monthly_report()